# Generated by Django 2.2.5 on 2020-01-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharednotebook',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notebookcomment',
            name='created_at',
            field=models.DateTimeField(default='2020-01-09 15:45:47+00:00'),
        ),
        migrations.AlterField(
            model_name='notebooklike',
            name='created_at',
            field=models.DateTimeField(default='2020-01-09 15:45:47+00:00'),
        ),
        migrations.AlterField(
            model_name='sharednotebook',
            name='created_at',
            field=models.DateTimeField(default='2020-01-02 15:45:47+00:00'),
        ),
        migrations.AlterField(
            model_name='sharednotebook',
            name='updated_at',
            field=models.DateTimeField(default='2020-01-02 15:45:47+00:00'),
        ),
    ]
