# Generated by Django 2.2.5 on 2020-02-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareddocument',
            name='document_type',
            field=models.TextField(default='notebook'),
        ),
        migrations.AlterField(
            model_name='documentcomment',
            name='created_at',
            field=models.DateTimeField(default='2020-02-17 18:26:57+00:00'),
        ),
        migrations.AlterField(
            model_name='documentlike',
            name='created_at',
            field=models.DateTimeField(default='2020-02-17 18:26:57+00:00'),
        ),
        migrations.AlterField(
            model_name='shareddocument',
            name='created_at',
            field=models.DateTimeField(default='2020-02-10 18:26:57+00:00'),
        ),
        migrations.AlterField(
            model_name='shareddocument',
            name='updated_at',
            field=models.DateTimeField(default='2020-02-10 18:26:57+00:00'),
        ),
    ]
