# Generated by Django 2.2.5 on 2020-02-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharednotebook',
            name='spaces',
            field=models.ManyToManyField(blank=True, related_name='spaces', to='gallery.HubSpace'),
        ),
        migrations.AlterField(
            model_name='notebookcomment',
            name='created_at',
            field=models.DateTimeField(default='2020-02-04 19:39:55+00:00'),
        ),
        migrations.AlterField(
            model_name='notebooklike',
            name='created_at',
            field=models.DateTimeField(default='2020-02-04 19:39:55+00:00'),
        ),
        migrations.AlterField(
            model_name='sharednotebook',
            name='created_at',
            field=models.DateTimeField(default='2020-01-28 19:39:55+00:00'),
        ),
        migrations.AlterField(
            model_name='sharednotebook',
            name='updated_at',
            field=models.DateTimeField(default='2020-01-28 19:39:55+00:00'),
        ),
    ]
