# Generated by Django 2.2.5 on 2020-06-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200217_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubuser',
            name='name',
            field=models.CharField(blank=True, max_length=70, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='documentcomment',
            name='created_at',
            field=models.DateTimeField(default='2020-06-11 18:54:32+00:00'),
        ),
        migrations.AlterField(
            model_name='documentlike',
            name='created_at',
            field=models.DateTimeField(default='2020-06-11 18:54:32+00:00'),
        ),
        migrations.AlterField(
            model_name='shareddocument',
            name='created_at',
            field=models.DateTimeField(default='2020-06-04 18:54:32+00:00'),
        ),
        migrations.AlterField(
            model_name='shareddocument',
            name='updated_at',
            field=models.DateTimeField(default='2020-06-04 18:54:32+00:00'),
        ),
    ]
