from django.urls import path
from . import views, views_document_details

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('login/', views.login_user, name='login-user'),
    path('delete-user/', views.delete_user, name='delete-user'),
    path('shared/', views.shared, name='shared'),
    path('logout/', views.logout_user, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('documents/', views.document_index, name='document-index'),
    path('search/', views.search_documents, name='search'),
    path('likes/', views.likes, name='likes'),
    path('sources/', views.data_source_index, name='data-source-index'),
    path('nbupload/', views.nbupload, name='nbupload'),
    path('document_by_source/', views.document_by_source, name='document_by_source'),
    path('document/<document_id>/', views_document_details.document_details, name='document-details'),
    path('open-document/<document_id>/', views_document_details.open_document_hub, name='open-document'),
    path('edit-document/<document_id>/', views.edit_document, name='edit-document'),
    path('render-document/<document_id>/', views_document_details.render_document, name='render-document'),
    path('delete-document/<document_id>/', views.delete_document, name='delete-document'),
    path('upload-document/', views.upload_document, name='upload-document'),
    path('download-document/<document_id>/', views.download_document, name='download-document'),
    path('add-comment/<document_id>/', views.add_comment, name='add-comment'),
    path('like-document/<document_id>/', views_document_details.like_document, name='like-document'),
    path('space/', views.spaces_index, name='spaces-index'),
    path('space/<space_id>/', views.spaces_details, name='space-details'),
    path('delete-space/<space_id>/', views.spaces_delete, name='space-delete'),
    path('edit-space-users/<space_id>/users/', views.spaces_users, name='space-users'),
]
