# Generated by Django 2.2.5 on 2020-01-07 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedNotebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notebook_name', models.TextField(default='')),
                ('notebook_content', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('tags', models.TextField(default='')),
                ('data_sources', models.TextField(default='')),
                ('views', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(default='2019-12-31 19:10:05+00:00')),
                ('created_at', models.DateTimeField(default='2019-12-31 19:10:05+00:00')),
                ('hub_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('master_notebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.SharedNotebook')),
            ],
        ),
        migrations.CreateModel(
            name='NotebookLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default='2020-01-07 19:10:05+00:00')),
                ('hub_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SharedNotebook')),
            ],
        ),
        migrations.CreateModel(
            name='NotebookComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(default='')),
                ('created_at', models.DateTimeField(default='2020-01-07 19:10:05+00:00')),
                ('hub_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SharedNotebook')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
