# Generated by Django 2.2.5 on 2020-01-07 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20180705_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebookcomment',
            name='oh_member',
        ),
        migrations.RemoveField(
            model_name='notebooklike',
            name='oh_member',
        ),
        migrations.RemoveField(
            model_name='sharednotebook',
            name='oh_member',
        ),
        migrations.AddField(
            model_name='notebookcomment',
            name='hub_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notebooklike',
            name='hub_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharednotebook',
            name='hub_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notebookcomment',
            name='created_at',
            field=models.DateTimeField(default='2020-01-07 14:58:58+00:00'),
        ),
        migrations.AlterField(
            model_name='notebooklike',
            name='created_at',
            field=models.DateTimeField(default='2020-01-07 14:58:58+00:00'),
        ),
        migrations.AlterField(
            model_name='sharednotebook',
            name='created_at',
            field=models.DateTimeField(default='2019-12-31 14:58:58+00:00'),
        ),
        migrations.AlterField(
            model_name='sharednotebook',
            name='updated_at',
            field=models.DateTimeField(default='2019-12-31 14:58:58+00:00'),
        ),
    ]
